// The test checks that stack after ArrayIndexOutOfBoundsException occurs is correct despite inlining
class Foo {
}
